### ISSUE TITLE
Add New Tag callback

### ISSUE THREAD

**Issue by stoppiNeobiz** [sarbagyastha/flutter_tagging#11]
Hi, there is a callback for Add New Tag button?

**Comment by sarbagyastha** [comment]
There's `additionCallback`.

**Comment by stoppiNeobiz** [comment]
in your example i see this:
```
additionCallback: (value) {
                return Language(
                  name: value,
                  position: 0,
                );
              },
```
but its call when i write on textbox, i want create a callback only for click on add new tag

**Comment by sarbagyastha** [comment]
Oh, you may use `onAdded` property then.
