### ISSUE TITLE
'TextFieldConfiguration' isn't a function

### ISSUE THREAD

**Issue by brizaldi** [sarbagyastha/flutter_tagging#13]
i got an error like this when i try code in example

`error: The name 'TextFieldConfiguration' is defined in the libraries 'package:flutter_typeahead/flutter_typeahead.dart' and 'package:flutter_typeahead_web/flutter_typeahead.dart (via package:flutter_tagging/flutter_tagging.dart)'. (ambiguous_import at ...)`

**Comment by sarbagyastha** [comment]
@brizaldi seems like you're using **flutter_typeahead** package too. The package already includes typeahead package.
