### ISSUE TITLE
 how to limit the number of tags?

### ISSUE THREAD

**Issue by sudeshkumara** [sarbagyastha/flutter_tagging#19]
Can I know how to limit the number of tags?
Also, thanks to this package.

**Comment by nitish-innovalabs** [comment]
Any luck with this?

**Comment by capriele** [comment]
Please check here: [pull request 25](https://github.com/sarbagyastha/flutter_tagging/pull/25)

**Comment by sudeshkumara** [comment]
> Please check here: [pull request 25](https://github.com/sarbagyastha/flutter_tagging/pull/25)

Thanks..🙌
