### ISSUE TITLE
Need Null Safety support

### ISSUE THREAD

**Issue by Basher7** [sarbagyastha/flutter_tagging#29]
**from flutter v2.0.2, flutter is now null-safety mechanism. Most of the packages already upgrade to null safety and more are upgrading.**

Thanks for this great package!

_Do you plan to make a null safe version of the package?_

**Comment by bradintheusa** [comment]
Looks like null-safety has been released but not checked in.

**Comment by kamalbanga** [comment]
@Basher7 Do you want to try out this alternate standalone implementation till then?
It doesn't depend on any library, just Flutter 2.0's `RawAutoComplete`; it therefore would also work on desktop.
[Link to `TagField` gist](https://gist.github.com/kamalbanga/4bab5edcbc876ad1ea5d0c078ce2c403)

<img width="210" alt="Screenshot 2021-11-13 at 11 06 56 AM" src="https://user-images.githubusercontent.com/3932617/141607206-3c53b9ac-61e2-45af-adc9-3340219283d7.png">
<img width="210" alt="Screenshot 2021-11-13 at 11 08 30 AM" src="https://user-images.githubusercontent.com/3932617/141607265-fedd3c13-0731-4a93-bc67-a3c470785db4.png">
