### ISSUE TITLE
Chip delete throws error

### ISSUE THREAD

**Issue by premy** [sarbagyastha/flutter_tagging#3]
When trying to delete an added chip I get this error

`I/flutter ( 4895): The following ConcurrentModificationError was thrown while handling a gesture:
I/flutter ( 4895): Concurrent modification during iteration: Instance(length:1) of '_GrowableList'.`

**Comment by Johnathon332** [comment]
Hi premy,

Not sure if you are still using this, but I have created a pull request for this issue.  Not sure when it will get reviewed and merged into master.

**Comment by MoacirSchmidt** [comment]
Please merge! I'm experimenting same issue!

**Comment by rhvmaster** [comment]
Same here

**Comment by sarbagyastha** [comment]
Package Revived #8
