### ISSUE TITLE
The argument type 'FlutterTagging can`t be assigned to the parameter type `Widget`

### ISSUE THREAD

**Issue by alex89607** [sarbagyastha/flutter_tagging#5]
I try to use and get error "The argument type 'FlutterTagging can`t be assigned to the parameter type `Widget`". It is only the simple code (example Hello, World + Firebase library, nothing more). Is it suppose to work at Web-version?

**Comment by alex89607** [comment]
Hi John. My troubles was depended on attempt to use widget at flutter-web mode with version "Flutter 1.7.8+hotfix.4". Now, it was changed mode (with use, for example, command "flutter run -d chrome" instead command "webdev serve" for starting application locally) and version (Flutter "1.9.1") and I left on time my my idea. But anyway thanks for answering.

**Comment by sarbagyastha** [comment]
Package Revived #8
